const fs = require('fs');
let file = fs.readFileSync('d:/FFSD/18_stockOverflow/final_ims/frontend/customer module/app-flow.js', 'utf8');

const regex = /          if \(mainImg && nextImgSrc\) \{\n            main\.innerHTML = '';\n            main\.appendChild\(mainImg\);\n            mainImg\.style\.display = '';\n            mainImg\.src = nextImgSrc;\n            return;\n          }\n\n    const ctaPrimary = document\.querySelector\('\.cta-primary'\);/s;

const newCode = "          if (mainImg && nextImgSrc) {\n            main.innerHTML = '';\n            main.appendChild(mainImg);\n            mainImg.style.display = '';\n            mainImg.src = nextImgSrc;\n            return;\n          }\n\n          if (!mainImg) {\n            main.textContent = thumb.textContent;\n          }\n        });\n      });\n    }\n\n    /* [Shopping Cart] Wire up the Add to Cart button */\n    const addBtn = document.getElementById('addToCartBtn');\n    if (addBtn) {\n      addBtn.addEventListener('click', (e) => {\n        e.preventDefault();\n        \n        const storeSelect = document.getElementById('detailStoreSelect');\n        if (storeSelect && !storeSelect.value) {\n          alert('Please select a store to reserve from!');\n          return;\n        }\n        \n        const storeId = storeSelect ? storeSelect.value : null;\n        const storeName = storeSelect ? storeSelect.options[storeSelect.selectedIndex].text : null;\n        \n        const sku = document.getElementById('breadcrumb-sku')?.textContent?.trim().split(' ').pop() || localStorage.getItem('imsSelectedSku') || 'UNKNOWN-SKU';\n        const name = document.getElementById('product-name')?.textContent?.trim() || localStorage.getItem('imsSelectedProduct') || 'Product';\n        const priceText = document.getElementById('spec-price')?.textContent || '.99'; \n        const price = parseFloat(priceText.replace(/[^0-9.]/g, '')) || 99.99;\n        \n        const mainImgEl = document.querySelector('#product-main-img');\n        const productImg = mainImgEl ? mainImgEl.getAttribute('src') : '';\n\n        window.addToCart({\n          sku,\n          name,\n          price,\n          productImg,\n          qty: 1,\n          storeId,\n          storeName\n        });\n      });\n    }\n  };\n\n  const wireConsumerLanding = () => {\n    const ctaPrimary = document.querySelector('.cta-primary');";

file = file.replace(regex, newCode);
fs.writeFileSync('d:/FFSD/18_stockOverflow/final_ims/frontend/customer module/app-flow.js', file);
